language: node_js
node_js:
  - "node"
install:
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/iota-pico/core.git https://github.com/iota-pico/core
  - cd https://github.com/iota-pico/core
  - npm link
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/iota-pico/api.git https://github.com/iota-pico/api
  - cd https://github.com/iota-pico/api
  - npm link @iota-pico/core
  - npm link
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/iota-pico/pal-browser.git https://github.com/iota-pico/pal-browser
  - cd https://github.com/iota-pico/pal-browser
  - npm link @iota-pico/core
  - npm link
  - cd ../api-examples-browser
  - npm link @iota-pico/core @iota-pico/api @iota-pico/pal-browser
  - npm install
script:
  - npm run dist || travis_terminate 1
#  - npm run security || travis_terminate 1
cache:
  directories:
    - "node_modules"
