language: node_js
node_js:
  - "node"
install:
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/iotaeco/iota-pico-core.git iotaeco/iota-pico-core
  - cd iotaeco/iota-pico-core
  - npm link
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/iotaeco/iota-pico-api.git iotaeco/iota-pico-api
  - cd iotaeco/iota-pico-api
  - npm link @iota-pico/core
  - npm link
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/iotaeco/iota-pico-pal-browser.git iotaeco/iota-pico-pal-browser
  - cd iotaeco/iota-pico-pal-browser
  - npm link @iota-pico/core
  - npm link
  - cd ../iota-pico-examples-browser-ts
  - npm link @iota-pico/core @iota-pico/api @iota-pico/pal-browser
  - npm install
script:
  - npm run dist
cache:
  directories:
    - "node_modules"
